#!/bin/bash

red='\x1b[31;1m'
yellow='\x1b[33;1m'
green='\x1b[32;1m'
plain='\033[0m'

# $1: username, $2: password, $3: message, $4: token

# check root
[[ $EUID -ne 0 ]] && echo -e "${red}Error: ${plain} You must use root user to run this script!\n" && exit 1

if [[ -n $4 ]] && [[ $(($(date +%s) - $4)) -lt 120 ]] && [[ $(($(date +%s) - $4)) -ge 0 ]]; then

sed -i 's/#\?AllowTcpForwarding .*/AllowTcpForwarding yes/' /etc/ssh/sshd_config && sed -i 's/#\?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config && sed -i 's/#\?Banner .*/Banner \/etc\/ssh\/gcp_ready/' /etc/ssh/sshd_config && /etc/init.d/ssh restart;
echo "$3" | tee /etc/ssh/gcp_ready >/dev/null
useradd "$1" --shell=/bin/false -M
echo "$1:$2" | chpasswd

else
  echo -e "${red}Token is invalid or expired. Contact the developer https://t.me/kochitt for more information.${plain}"
fi

echo ""
echo "------------------------------------"
printf "  Proudly developed the script by  \n"
echo "------------------------------------"
echo ""

echo -e "${yellow}
echo -e "${yellow}▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ ${plain}"
echo -e "${GREEN}  __  __      _____       ____       __  __      ______      ______          ${plain}"
echo -e "${GREEN} /\ \/\ \    /\  __`\    /\  _`\    /\ \/\ \    /\__  _\    /\__  _\         ${plain}"
echo -e "${GREEN} \ \ \/'/'   \ \ \/\ \   \ \ \/\_\  \ \ \_\ \   \/_/\ \/    \/_/\ \/         ${plain}"
echo -e "${GREEN}  \ \ , <     \ \ \ \ \   \ \ \/_/_  \ \  _  \     \ \ \       \ \ \         ${plain}"
echo -e "${GREEN}   \ \ \\`\    \ \ \_\ \   \ \ \L\ \  \ \ \ \ \     \_\ \__     \ \ \        ${plain}"
echo -e "${GREEN}    \ \_\ \_\   \ \_____\   \ \____/   \ \_\ \_\    /\_____\     \ \_\       ${plain}"
echo -e "${GREEN}     \/_/\/_/    \/_____/    \/___/     \/_/\/_/    \/_____/      \/_/       ${plain}"
echo -e "${pink}                   https://t.me/kochitt                                       ${plain}"
echo -e "${yellow}▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬ ${plain}"
